require: rubocop-rspec

# Autocorrection spec
Rails:
  Enabled: true

# Disable default-comment
Style/FrozenStringLiteralComment:
  Enabled: false

# The max row size
Metrics/LineLength:
  Max: 250

# Disabling comments for classes and  methods
Style/Documentation:
  Enabled: false

# The max size for methods
Metrics/MethodLength:
  Max: 30